Adds script for generating NCR shapefiles for GeoServer.
ua-snap/geospatial-vector-veracity pull request #106
Opened 2023-03-16 20:00 UTC by BobTorgerson

This PR creates the required shapefiles for upload to Geoserver for all NCR and ArcticEDS places and AOIs. 

To test, go into utilities and run:

python create_updated_ncr_shapefiles.py

After a few minutes, 3 shapefiles and their associated additional files will be present in the directory: utilities/all_places/

2023-03-31 22:23 UTC, brucecrevensten requested changes

2023-10-31 00:59 UTC, cstephen commented on utilities/create_updated_ncr_shapefiles.py
>  communities.to_file("all_places/all_communities.shp", encoding="utf-8")
I'm not getting this warning when I run `create_updated_ncr_shapefiles.py`, FWIW.

2023-10-31 01:05 UTC, cstephen commented
I went ahead and tacked my work with the new Yukon areas onto this branch, pulling in the new Yukon area shapefiles from the `add-yt-polygons` branch.

I see some unresolved comments in this PR, but I'm pretty sure we'll want to merge this branch as-is without any additional changes that could impact the API or NCR in unexpected ways, such as changing the `huc` type to `huc8` for example.

Xref: https://github.com/ua-snap/northern-climate-reports/pull/633
Xref: https://github.com/ua-snap/data-api/pull/407

2023-12-19 15:32 UTC, brucecrevensten commented
OK, merging as-is, thanks @cstephen

2023-12-19 15:32 UTC, merged